### ISSUE TITLE
Todo lijst

### ISSUE THREAD

**Issue by hkrutzer** [tom1944/planar-graphs#1]
- [ ] Bepalen of er voor input n en m een simple graph gemaakt kan worden
- [x] Random graph maken (dmv networkx)
- [x] Thickness bepalen
- [x] Bepalen of graph planar is
- [x] Tekenen van de graph in planaire vorm mbv networkx
- [ ] Wellicht zelf planaire tekenen
- [ ] Testset maken
- [ ] Eventueel complexiteit van algoritmes precies bepalen
